[package]
name = "rb-sys-tests"
version = "0.9.20"
edition = "2018"
autotests = false
publish = false

[lib]
bench = false
doctest = false  
doc = false

[features]
default = ["ruby-macros"]
ruby-macros = ["rb-sys/ruby-macros"]

[dependencies]
rb-sys = { path = "../rb-sys", features = ["link-ruby"] }
ctor = "0.1"

[build-dependencies]
rb-sys-build = { path = "../rb-sys-build" }