[package]
name = "rb-sys-tests"
version = "0.9.11"
edition = "2018"
autotests = false
publish = false

[dependencies]
rb-sys = { path = "../rb-sys" } 
ctor = "0.1"

[features]
link-ruby = ["rb-sys/link-ruby"]
ruby-macros = ["rb-sys/ruby-macros"]

[[test]]
name = "rb-sys-tests"
path = "tests/lib.rs"
harness = true
required-features = ["link-ruby", "ruby-macros"]