---
name: "CI"

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: ðŸ’… Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: stable
          ruby_version: "3.1"
          os: ubuntu-latest
      - uses: actions-rs/cargo@v1
        name: âœ‚ï¸ Run clippy
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: ðŸ“ƒ Run cargo fmt
        with:
          command: fmt
          args: --check
      - name: ðŸš“ Run Standard.rb
        run: bundle exec standardrb --format github

  build_and_test:
    name: ðŸ§ª Build and test
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.6", "2.7", "3.0", "3.1", "head"]
        sys:
          - os: ubuntu-latest
            rust_toolchain: stable
          - os: macos-latest
            rust_toolchain: stable
          - os: windows-2019
            rust_toolchain: stable-x86_64-pc-windows-gnu
    runs-on: ${{ matrix.sys.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: ${{ matrix.sys.rust_toolchain }}
          ruby_version: ${{ matrix.ruby_version }}
          os: ${{ matrix.sys.os }}
      - name: ðŸ§ª Cargo test
        run: bundle exec rake test:cargo
      - name: ðŸ’Ž Gem test
        run: bundle exec rake test:gem
      - name: ðŸ’¨ Smoke test
        env:
          PROFILE: "release"
        run: |
          bundle exec rake test:examples

  build_and_test_static:
    name: ðŸ”˜ Test static Ruby
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.1.2"]
        sys:
          - os: ubuntu-latest
            rust_toolchain: stable
    runs-on: ${{ matrix.sys.os }}
    steps:
      - uses: actions/checkout@v3
      - name: âš¡ Cache
        uses: actions/cache@v3
        with:
          path: |
            /opt/rubies/${{ matrix.ruby_version }}
            ~/.gem/ruby/${{ matrix.ruby_version }}
        key: ${{ matrix.sys.os }}-${{ matrix.ruby_version }}
      - name: Setup env
        run: |
          echo "PATH=/opt/rubies/${{ matrix.ruby_version }}/bin:$PATH" >> $GITHUB_ENV
          echo "GEM_HOME=~/.gem/ruby/${{ matrix.ruby_version }}" >> $GITHUB_ENV
      - name: ðŸ”˜ Build static ruby
        working-directory: /tmp
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          PREFIX=/usr/local sudo ./ruby-build/install.sh
          RUBY_CONFIGURE_OPTS="--disable-shared --disable-install-doc" sudo ruby-build ${{ matrix.ruby_version }} /opt/rubies/${{ matrix.ruby_version }} --verbose
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: ${{ matrix.sys.rust_toolchain }}
          ruby_version: skip
          os: ${{ matrix.sys.os }}
      - name: ðŸ§ª Run tests
        run: bundle exec rake test
