---
name: CI

on: [push]

jobs:
  lint:
    name: ğŸ’… Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: stable
          ruby_version: '3.0'
          os: ubuntu-latest
      - uses: actions-rs/cargo@v1
        name: âœ‚ï¸ Run clippy
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: ğŸ“ƒ Run cargo fmt
        with:
          command: fmt

  build_and_test:
    name: ğŸ§ª Build and test
    env:
      RUBY_LINK: "true"
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby_version: ['2.4', '2.5', '2.6', '2.7', '3.0', '3.1']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: ${{ matrix.rust_toolchain }}
          ruby_version: ${{ matrix.ruby_version }}
          os: ${{ matrix.os }}
      - name: â³ Install libclang
        run: pacman -S mingw-w64-x86_64-clang
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: actions-rs/cargo@v1
        name: ğŸ›  Cargo build
        with:
          command: build
          args: --locked --release --verbose 
      - uses: actions-rs/cargo@v1
        name: ğŸ§ª Cargo test
        if: ${{ matrix.os != 'windows-latest' }}
        with:
          command: test
      - name: ğŸ’¨ Smoke test 
        if: ${{ matrix.os != 'windows-latest' }}
        working-directory: examples/simple
        run: cargo make verify --verbose