---
on: [push]
name: CI
jobs:
  lint:
    name: ğŸ’… Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          rust_toolchain: stable
          ruby_version: '3.0'
          os: ubuntu-latest
      - uses: actions-rs/cargo@v1
        name: âœ‚ï¸ Run clippy
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: ğŸ“ƒ Run cargo fmt
        with:
          command: fmt

  run_tests:
    name: Ruby ${{ matrix.ruby }} | Rust ${{ matrix.rust_toolchain}} | OS ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust_toolchain: [stable]
        os: [ubuntu-latest, macos-latest]
        ruby_version: ['2.6', '2.7', '3.0', '3.1']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ./.github/actions/setup.yml
        with:
          rust_toolchain: ${{ matrix.rust_toolchain }}
          ruby_version: ${{ matrix.ruby_version }}
          os: ${{ matrix.os }}
      - uses: actions-rs/cargo@v1
        name: ğŸ›  Cargo build
        with:
          command: build
          args: --locked --release --verbose 
      - uses: actions-rs/cargo@v1
        name: ğŸ§ª Cargo test
        with:
          command: test
      - name: ğŸ’¨ Smoke test 
        working-directory: examples/simple
        run: cargo make verify --verbose