---
name: "CI"

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: ğŸ’… Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: stable
          ruby_version: "3.1"
          os: ubuntu-latest
      - uses: actions-rs/cargo@v1
        name: âœ‚ï¸ Run clippy
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: ğŸ“ƒ Run cargo fmt
        with:
          command: fmt
          args: --check
      - name: ğŸš“ Run Standard.rb
        run: bundle exec standardrb --format github

  build_and_test:
    name: ğŸ§ª Build and test
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["2.6", "2.7", "3.0", "3.1", "head"]
        sys:
          - os: ubuntu-latest
            rust_toolchain: stable
          - os: macos-latest
            rust_toolchain: stable
          - os: windows-2019
            rust_toolchain: stable-x86_64-pc-windows-gnu
    runs-on: ${{ matrix.sys.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: ${{ matrix.sys.rust_toolchain }}
          ruby_version: ${{ matrix.ruby_version }}
          os: ${{ matrix.sys.os }}
      - name: ğŸ§ª Cargo test
        run: bundle exec rake test:cargo
      - name: ğŸ’ Gem test
        run: bundle exec rake test:gem
      - name: ğŸ’¨ Smoke test
        env:
          PROFILE: "release"
        run: |
          bundle exec rake test:examples

  build_and_test_static:
    name: ğŸ§ª Build and test
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.1.2"]
        sys:
          - os: ubuntu-latest
            rust_toolchain: stable
    runs-on: ${{ matrix.sys.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
        with:
          rust_toolchain: ${{ matrix.sys.rust_toolchain }}
          ruby_version: ${{ matrix.ruby_version }}
          os: ${{ matrix.sys.os }}
      - name: ğŸŒ« Build static ruby
        working-directory: ./tmp
        run: |
          git clone https://github.com/rbenv/ruby-build.git
          PREFIX=/usr/local ./ruby-build/install.sh
          RUBY_CONFIGURE_OPTS="--disable-shared" ruby-build ${{ matrix.ruby_version }} /usr/local --verbose
      - name: ğŸ§ª Run tests
        run: bundle exec rake test
