---
on: [push]

name: CI

jobs:
  build_and_test:
    name: Build and test 
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['2.6.9', '2.7.5', '3.0.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: âš¡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            examples/simple/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: ğŸªŸ Setup msys2
        uses: msys2/setup-msys2@v2
        if: ${{ matrix.os == 'windows-latest' }}

      # - name: ğŸ¥Š Fix pkg-config for Windows 
      #   run: |
      #     pacman -S --overwrite '*' mingw-w64-x86_64-pkg-config
      #   if: ${{ matrix.os == 'windows-latest' }}

      - name: ğŸª² Debug Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          which pkg-config

      - uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        name: ğŸ›  Cargo build
        with:
          command: build
          args: --verbose 

      - uses: actions-rs/cargo@v1
        name: ğŸ§ª Cargo test
        with:
          command: test

      - name: â“‚ï¸ Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: ğŸ’¨ Smoke test 
        working-directory: examples/simple
        run: cargo make verify --verbose